services:
  meeting-service:
    build:
      context: .
    container_name: meeting-service-act-3
    ports:
      - "8080:8000"
    volumes:
      - .:/var/www/html
    develop:
      watch:
        - path: .
          target: /var/www/html
          action: sync
        - path: ./composer.json
          action: rebuild
        - path: ./composer.lock
          action: rebuild
    depends_on:
      - mongodb
      - postgresql

  mongodb:
    image: mongo:latest
    container_name: meeting-mongodb-Act-3
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootPassword
      MONGO_INITDB_DATABASE: miranda_mongodb
    ports:
      - "27171:27017"
    volumes:
      - meeting-mongodb:/data/db/mongodb

  postgresql:
    image: postgres:15
    container_name: meeting-postgresql-Act-3
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: miranda_postgresql
    ports:
      - "5121:5432"
    volumes:
      - meeting-postgresql:/data/db/postgresql

volumes:
  meeting-mongodb:
    driver: local
  meeting-postgresql:
    driver: local
